/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Verify that the conditions for a release are satisfied.
 *
 * The conditions for a release checked by this function are:
 *
 *    1. That the cargo registry token has been defined (skipped in prepare-only mode).
 *    2. That it can construct the graph of all of the dependencies in the
 *       workspace.
 *    3. That the dependencies and build-dependencies of all of crates in the
 *       workspace are suitable for publishing to `crates.io`.
 *
 * If `manifest_path` is provided then it is expect to give the path to the
 * `Cargo.toml` file for the root of the workspace. If `manifest_path` is `None`
 * then `verify_conditions` will look for the root of the workspace in a
 * `Cargo.toml` file in the current directory. If one of the conditions for a
 * release are not satisfied then an explanation for that will be written to
 * `output`.
 *
 * This implements the `verifyConditions` step for `semantic-release` for a
 * Cargo-based rust workspace.
 */
export declare function verifyConditions(opts?: PublishArgs | undefined | null): void
/**
 * Prepare the Rust workspace for a release.
 *
 * Preparing the release updates the version of each crate in the workspace and of
 * the intra-workspace dependencies. The `version` field in the `packages` table of
 * each `Cargo.toml` file in the workspace is set to the supplied version. The
 * `version` field of each dependency, build-dependency and dev-dependency that
 * is otherwise identified by a workspace-relative path dependencies is also set
 * to the supplied version (the version filed will be added if it isn't
 * already present).
 *
 * This implements the `prepare` step for `semantic-release` for a Cargo-based Rust
 * workspace.
 */
export declare function prepare(nextReleaseVersion: string): void
/** Arguments to be passed to the `publish` function and reused for `verifyConditions`. */
export interface PublishArgs {
  /** Whether the `--no-dirty` flag should be passed to `cargo publish`. */
  noDirty?: boolean
  /** A map of packages and features to pass to `cargo publish`. */
  features?: Record<string, Array<string>>
  /** Optionally passes a `--registry` flag `cargo publish`. */
  registry?: string
  /**
   * When `Some(false)`, publishing is disabled (prepare-only mode): no packages
   * are uploaded.
   */
  publish?: boolean
}
/**
 * Publish the publishable crates from the workspace.
 *
 * The publishable crates are the crates in the workspace other than those
 * whose `package.publish` field is set to `false` or that includes a registry other
 * than `crates.io`.
 *
 * This implements the `publish` step for `semantic-release` for a Cargo-based
 * Rust workspace.
 */
export declare function publish(opts?: PublishArgs | undefined | null): void
